FROM alpine:3.18
RUN apk add --no-cache bash curl python3 build-base
ENV NVM_DIR=/root/.nvm NODE_VERSION=23.3.0
SHELL ["/bin/bash", "-c"]

RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash \
  && source $NVM_DIR/nvm.sh \
  && nvm install v${NODE_VERSION} \
  && nvm alias default v${NODE_VERSION} \
  && nvm use default

RUN source $NVM_DIR/nvm.sh && npm install -g pnpm

WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN source $NVM_DIR/nvm.sh && pnpm install
COPY . .
RUN source $NVM_DIR/nvm.sh && pnpm run build

CMD ["/bin/bash", "-c", "source /root/.nvm/nvm.sh && pnpm run lint"]
